name: First Workflow
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a build step
        run: echo Hello, world!

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a test step
        run: echo Hello, world!
